#!/usr/bin/env python3

import argparse
import re
import sys
import yaml

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import NoReturn


@dataclass(frozen=True)
class NationDefinition:
    name: str
    texture: str


@dataclass(frozen=True)
class Configuration:
    version: int
    nation_types: tuple[NationDefinition, ...]


NAME_PATTERN = re.compile(r"[a-z][a-z0-9]*(?:_[a-z0-9]+)*")


def load_yaml(path: Path) -> object:
    try:
        with path.open(encoding="utf-8") as file:
            return yaml.safe_load(file)
    except OSError as error:
        raise RuntimeError(f"cannot read {path}: {error}") from error
    except yaml.YAMLError as error:
        raise RuntimeError(f"invalid YAML in {path}: {error}") from error


def config_error(location: str, message: str) -> NoReturn:
    raise RuntimeError(f"{location}: {message}")


def validate_name(value: object, location: str) -> str:
    if not isinstance(value, str):
        config_error(location, "expected a string")

    if NAME_PATTERN.fullmatch(value) is None:
        config_error(
            location,
            "expected a lowercase name containing letters, digits, "
            "and single underscores"
        )

    return value


def parse_config(document: object) -> Configuration:
    if not isinstance(document, Mapping):
        config_error("<root>", "expected a mapping")

    required_root_fields = {"version", "nation_types"}

    unknown_root_fields = set(document) - required_root_fields
    if unknown_root_fields:
        names = ", ".join(
            sorted(repr(field) for field in unknown_root_fields)
        )
        config_error("<root>", f"unknown fields: {names}")

    missing_root_fields = required_root_fields - set(document)
    if missing_root_fields:
        names = ", ".join(sorted(missing_root_fields))
        config_error("<root>", f"missing fields: {names}")

    version = document["version"]

    if type(version) is not int:
        config_error("version", "expected an integer")

    if version != 1:
        config_error(
            "version",
            f"unsupported version {version}; expected 1"
        )

    raw_nation_types = document["nation_types"]
    if not isinstance(raw_nation_types, Mapping):
        config_error("nation_types", "expected a mapping")

    if not raw_nation_types:
        config_error("nation_types", "must contain at least one nation type")

    nation_types: list[NationDefinition] = []

    for raw_nation_name, raw_nation in raw_nation_types.items():
        nation_name = validate_name(
            raw_nation_name,
            "nation_types.<name>",
        )
        nation_location = f"nation_types.{nation_name}"

        if not isinstance(raw_nation, Mapping):
            config_error(nation_location, "expected a mapping")

        allowed_nation_fields = {"texture"}
        unknown_nation_fields = set(raw_nation) - allowed_nation_fields
        if unknown_nation_fields:
            names = ", ".join(
                sorted(repr(field) for field in unknown_nation_fields)
            )
            config_error(nation_location, f"unknown fields: {names}")

        if "texture" not in raw_nation:
            config_error(nation_location, "missing field 'texture'")

        texture = validate_name(
            raw_nation["texture"],
            f"{nation_location}.texture",
        )

        nation_types.append(
            NationDefinition(name=nation_name, texture=texture)
        )

    return Configuration(
        version=version,
        nation_types=tuple(nation_types),
    )


def generate_header(config: Configuration) -> str:
    lines: list[str] = []

    lines.extend([
        "// Generated file. Do not edit.",
        "// Generated by tools/python/generate_actor_data.py.",
        "",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "enum class NationType : std::uint16_t {",
    ])

    for nation in config.nation_types:
        lines.append(f"    {nation.name},")

    lines.extend([
        "};",
        "",
        f"inline constexpr std::size_t NATION_TYPE_COUNT = "
        f"{len(config.nation_types)};",
        "",
        "struct ActorData {",
        "    std::string_view texture_name;",
        "};",
        "",
        "inline constexpr",
        "std::array<ActorData, NATION_TYPE_COUNT> actor_data{{",
    ])

    for nation in config.nation_types:
        lines.extend([
            f"    // NationType::{nation.name}",
            f'    ActorData{{ .texture_name = "{nation.texture}" }},',
        ])

    lines.extend([
        "}};",
        "",
        "[[nodiscard]]",
        "inline constexpr std::string_view",
        "get_nation_type_string(NationType type) noexcept",
        "{",
        "    switch (type)",
        "    {",
    ])

    for nation in config.nation_types:
        lines.append(
            f'        case NationType::{nation.name}: return "{nation.name}";'
        )

    lines.extend([
        "    }",
        "",
        "    return {};",
        "}",
        "",
        "[[nodiscard]]",
        "inline constexpr const ActorData&",
        "get_actor_data(NationType type) noexcept",
        "{",
        "    return actor_data[static_cast<std::size_t>(type)];",
        "}",
        "",
    ])

    return "\n".join(lines)


def write_if_changed(path: Path, contents: str) -> None:
    try:
        if path.read_text(encoding="utf-8") == contents:
            return
    except FileNotFoundError:
        pass

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate C++ actor data from YAML."
    )
    parser.add_argument("input_path", type=Path)
    parser.add_argument("output_path", type=Path)
    arguments = parser.parse_args()

    document = load_yaml(arguments.input_path)
    config = parse_config(document)
    header = generate_header(config)
    write_if_changed(arguments.output_path, header)


if __name__ == "__main__":
    try:
        main()
    except RuntimeError as error:
        print(f"generate_actor_data: error: {error}", file=sys.stderr)
        raise SystemExit(1)
