#+TITLE: Last Ditch Documentation

Last Ditch: The Garden of Nations


* Overview

Last Ditch is a simulation of [[Nation]]s acting under the leadership of a [[Judge]].

The player controls the [[Judge]], but the [[Role]] can be passed on to other [[Citizen]]s. All [[Agent]]s behave according to their own will, taking into account [[Enforcement]] of the [[Law]]s.

The setting is at the top of a Carrier Hotel in a ruined technological world. Each [[Nation]] attempts to progress by reclaiming parts from the floors below in order to build on the [[Tower]] roof.


* Judgment

Each [[Nation]] has a [[Judge]] who leads using [[Law]]s.

** Traits
- Loyalty
- Fear
- Love
- Respect
  
** Succession

A [[Judge]] can choose their [[Successor]], but leadership may pass to another [[Citizen]] if the [[Judge]] does not have enough Loyalty.

A [[Challenger]] can also arise.


* Laws

A set of [[Law]]s is how the player interacts with the civilization as a [[Judge]].

** Civil

Civil Laws

** Military

Military Laws

** Economic

Economic Laws


* Nations

There are four [[Nation]]s.

1. <<Wolf>>
   The Eastern nation.
   
2. <<Eagle>>
   The Western nation.

3. <<Bear>>
   The Northern nation.

4. <<Lion>>
   The Southern nation.

* The Tower

The tower is a ruined Carrier Hotel that serves as the setting for Last Ditch. The [[Nation]]s all build on the roof of the tower, and they gather parts from the upper floors below.

The closest levels to the top are the safest with relatively harmless [[Scavenger]]s present, but the lower floors have increasingly more dangerous forces present, alongside more valuable material.

   
* Architecture

Each [[Nation]] builds structures to support itself. These can be designed by the [[Judge]] using Architecting tools.

Depending on the strictness of Civil [[Law]]s, [[Citizen]]s will customize the architectural plans to varying degrees.


* Keywords

<<Tower>>
The Carrier Hotel

<<Nation>>
A population of [[Citizen]]s living under a [[Judge]].

<<Agent>>
Any actor in the world.

<<Judge>>
The [[Citizen]] who issues a set of [[Law]]s.

<<Successor>>
The heir apparent of the [[Judge]].

<<Challenger>>
A [[Citizen]] attempting to take leadership from the existing [[Judge]].

<<Citizen>>
A member of a [[Nation]].

<<Scavenger>>
An [[Agent]] without a [[Nation]].

<<Role>>
A [[Citizen]]'s specialization.

<<Law>>
A constraint on the behavior of [[Citizen]]s.

<<Enforcement>>
The process by which the [[Law]]s are applied.

<<Architecture>>
The design of the structures that are built by each [[Nation]].
