#+TITLE: Last Ditch Documentation

Last Ditch: The Garden of Nations

* Overview

Last Ditch is a simulation of [[Nation]]s acting under the leadership of a [[Judge]].

The player controls only the [[Judge]], but the [[Role]] can be passed on to other [[Citizen]]s. All [[Citizen]]s behave according to their own will, taking into account the [[Rule]]s to the degree they deem appropriate based on their individual character traits. 

* Judgment
Each [[Nation]] has a [[Judge]] who leads using [[Rule]]s.

** Traits
- Loyalty
- Fear
- Love
- Respect

** Succession

A [[Judge]] can choose their [[Successor]], but leadership may pass to another [[Citizen]] if the [[Judge]] does not have enough Loyalty.

A [[Challenger]] can also arise.

** 

* Rules
A set of [[Rule]]s is how the player interacts with the civilization as a [[Judge]].

** Categories

*** Civil

Civil Rules

*** Military

Military Rules

*** Economic

Economic Rules

* Nations
There are four [[Nation]]s.

1. <<Wolf>>
   The Eastern nation.
   
2. <<Eagle>>
   The Western nation.

3. <<Bear>>
   The Northern nation.

4. <<Lion>>
   The Southern nation.

* Architecture

Each [[Nation]] builds structures to support itself. These can be designed by the [[Judge]] using Architecting tools.

Depending on the strictness of Civil [[Rule]]s, [[Citizen]]s will customize the architectural plans to varying degrees.
   
* Keywords

<<Nation>>
A population of [[Citizen]]s living under a [[Judge]].

<<Role>>
A [[Citizen]]'s specialization.

<<Judge>>
The [[Citizen]] who issues a set of [[Rule]]s.

<<Successor>>
The heir apparent of the [[Judge]].

<<Challenger>>
A [[Citizen]] attempting to take leadership from the existing [[Judge]].

<<Citizen>>
A member of a [[Nation]].

<<Rule>>
A constraint on the behavior of [[Citizen]]s.

<<Architecture>>
The design of the structures that are built by each [[Nation]].


